spring:
  application:
    name: user-service

  config:
    import:
      - vault://
      - optional:configserver:http://config-service:8888

  cloud:
    vault:
      uri: http://vault:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: rideshare
        default-context: ${spring.application.name}
        application-name: application
